// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(router) {
    return router.get("/", function(req, res) {
      return res.render('index', {
        title: 'Express!!@@:)'
      });
    });
  };

}).call(this);
