// Generated by CoffeeScript 1.9.3
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET home page. */

  router.get('/', function(req, res, next) {
    var User;
    User = GLOBAL.db.User;
    console.log(User);
    return User.findAll().then(function(result) {
      return res.json(result);
    });
  });

  module.exports = router;

}).call(this);
