// Generated by CoffeeScript 1.9.3
(function() {
  var JSONRenderer, User;

  JSONRenderer = require('../lib/jsonRenderer');

  User = GLOBAL.db.User;

  module.exports = function(router) {
    return router.get('/users', function(req, res, next) {
      console.log('Hello Users');
      return User.findAll().then(function(users) {
        return res.json(JSONRenderer.users(users));
      });
    });
  };

}).call(this);
