// Generated by CoffeeScript 1.9.3
(function() {
  var JsonRenderer, exports;

  JsonRenderer = {
    user: function(user) {
      return {
        id: user.id,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        updated_at: user.updated_at,
        created_at: user.created_at
      };
    },
    users: function(users) {
      var data, i, len, user;
      data = [];
      for (i = 0, len = users.length; i < len; i++) {
        user = users[i];
        data.push(this.user(user));
      }
      return data;
    }
  };

  exports = module.exports = JsonRenderer;

}).call(this);
