// Generated by CoffeeScript 1.9.3
(function() {
  var config, environment, exports, fs;

  fs = require("fs");

  environment = process.env.NODE_ENV || "development";

  config = JSON.parse(fs.readFileSync(process.cwd() + "/config.json", "utf8"))[environment];

  exports = module.exports = function() {
    return config;
  };

}).call(this);
