// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  module.exports = function(sequelize, DataTypes) {
    var BankWithdrawal;
    BankWithdrawal = sequelize.define('BankWithdrawal', {
      amount: DataTypes.FLOAT,
      status: DataTypes.BOOLEAN,
      is_mail_sent: DataTypes.BOOLEAN,
      bank_address: DataTypes.STRING,
      iban: DataTypes.STRING,
      bic: DataTypes.STRING,
      swift: DataTypes.STRING,
      email: DataTypes.STRING
    }, {
      classMethods: {
        associate: function(models) {}
      }
    });
    return BankWithdrawal;
  };

}).call(this);
