// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  module.exports = function(sequelize, DataTypes) {
    var Task;
    Task = sequelize.define('Task', {
      name: DataTypes.STRING,
      status: DataTypes.INTEGER,
      date: DataTypes.DATE
    }, {
      underscored: true,
      timestamps: true,
      classMethods: {
        associate: function(models) {
          return Task.belongsTo(models.User);
        }
      }
    });
    return Task;
  };

}).call(this);
