// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  module.exports = function(sequelize, DataTypes) {
    var TaskTest;
    TaskTest = sequelize.define('TaskTest', {
      name: DataTypes.STRING,
      status: DataTypes.INTEGER,
      date: DataTypes.DATE
    }, {
      classMethods: {
        associate: function(models) {}
      }
    });
    return TaskTest;
  };

}).call(this);
