// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  module.exports = function(sequelize, DataTypes) {
    var User;
    User = sequelize.define('User', {
      firstName: DataTypes.STRING,
      lastName: DataTypes.STRING,
      password: DataTypes.STRING,
      salt: DataTypes.STRING,
      user_token: DataTypes.STRING,
      is_active: DataTypes.BOOLEAN,
      email: DataTypes.STRING
    }, {
      tableName: "Users",
      underscored: true,
      timestamps: true,
      classMethods: {
        associate: function(models) {
          return User.hasMany(models.Task);
        },
        findById: function(id, callback) {
          if (callback == null) {
            callback = function() {};
          }
          return User.find(id).complete(callback);
        },
        findByEmail: function(email, callback) {
          return User.find(email).complete(callback);
        }
      }
    });
    return User;
  };

}).call(this);
